### ISSUE TITLE
move types to fidel defaults

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/mask#4]
lets move types to:

```
$.declare('mask', {
  defaults: {
    types: {
      ssn: {}
    }
  }
});
```

that way they can be extended and changed with either `$().mask({ types: })` or `$.fn.mask.defaults.types.blah = {};`

**Comment by dawnerd** [comment]
Tried default.types but it doesn't look like fidel does a deep extend so it removes the other defaults.

So for now it's just defaults.ssn, etc

**Comment by jgallen23** [comment]
K
